### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [jenniferpiz/NYTimesSearch#1]
Nice work overall. A few notes after checking out the code:

* Properly reused the single base method in search activity to fetch results for both initial load and the pagination
* Properly used spinners/checkboxes (with populated values) to allow users to select filters
* Nice to see you added the search box to the `Toolbar`!
* Good to see you used a filters object to represent the filters to apply to the query
* Make sure to try out creating a [date picker](http://guides.codepath.com/android/Using-DialogFragment#displaying-date-or-time-picker-dialogs) dialog. 
* Nice job adding the share intent to the article detail view!

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by jenniferpiz** [comment]
Hello!  Thanks for the quick feedback.  I implemented the date picker dialog as described in the guide using  the DatePickerFragment.  The whole calendar dialog was showing in the IDE Emulator.  For some reason, the Genymotion is only showing the spinner type date picker.  I thought this is specific to emulator so I didn't bother to further improve it.

**Comment by jenniferpiz** [comment]
<img width="336" alt="screen shot 2017-09-24 at 10 50 42 pm" src="https://user-images.githubusercontent.com/30905817/30794066-eef715e0-a17a-11e7-9547-6979eef5a373.png">

**Comment by codepathreview** [comment]
Thanks for the clarification, Jennifer. It doesn't change/cut any marks to use either way, this is just something better for a good user experience.
